cloud-gov/common-pipelines

README.md
- See title
None; documentation change only.
=> Improve troubleshooting guidance

container/examples/cloud-gov-repo/ci/vars.yml, container/pipeline-external-repository.yml, container/pipeline.yml
See https://github.com/cloud-gov/set-container-pipelines
- See title. 
- Examples to be updated in follow-up PR.
None.
=> Pipelines will now be set by parent pipeline

container/cve-check.yml, container/pipeline-external-repository.yml, container/pipeline.yml, container/scan-image.yml
- See title
Very meta, updating our pipelines that harden our containers to also use hardened containers
=> Update pipelines to use hardened containers

container/dockerfiles/semver-resource/Dockerfile
- Removed line added in error.
-
-
There are no security considerations for this change
=> Removed line added in error.

container/dockerfiles/email-resource/Dockerfile
- Adds dockerfile for building the email-resource image
None, just adding the Dockerfile used to create the email-resource image
=> Add email resource

container/README.md
- Whitespace commit inside container folder so it is signed by the new gpg key
-
-
None
=> New GPG Key whitespace

ci/container/external/github-pr-resource/vars.yml
- Attempting to test local patch of taskfile from version 2 to 3 on a forked repo of github-pr-resource
-
-
None
=> Switch to forked/patched resource

ci/container/internal/playwright/vars.yml, ci/container/pipeline.yml
=> add playwright image

ci/container/external/cloud-service-broker/vars.yml
- Minor fixes; see title
- Related to https://github.com/cloud-gov/product/issues/2943
None
=> scr-target-branch is required, and dockerfile change should trigger rebuild

container/dockerfiles/cloud-service-broker/Dockerfile
=> Test with more basic Dockerfile

container/dockerfiles/cloud-service-broker/Dockerfile
Also name binary "csb", which is easier to type
None.
=> Support colocating brokerpaks with broker binary using dedicated folder

ci/container/internal/csb/vars.yml, ci/container/pipeline.yml
Related to https://github.com/cloud-gov/product/issues/2943
Related to https://github.com/cloud-gov/csb/pull/1
None.
=> Build our custom csb image, with brokerpaks included

ci/container/pages/redis-v7.2/vars.yml, ci/container/pipeline.yml
- add pages redis image
Noted in https://github.com/cloud-gov/pages-images/pull/11
=> Add pages redis image

ci/container/pages/postgres-v15/vars.yml, ci/container/pipeline.yml
- Add pages postgres image
New hardened image for pages CI use
=> Add pages postgres image

ci/container/pages/nginx-v1/vars.yml, ci/container/pipeline.yml
- Add pages nginx image
Additional pages hardened image
=> Add pages nginx image

ci/container/external/bosh-io-stemcell-resource/vars.yml, ci/container/pipeline.yml
- Creates a pipeline for hardening the bosh-io-stemcell-image
Adding pipeline for bosh-io-stemcell-image
=> add bosh io stemcell resource

ci/container/external/pool-resource/vars.yml, ci/container/pipeline.yml
- Add code to create pipeline to harden pool-resource image
Create pipeline to harden pool-resource image
=> add pool-resource

container/dockerfiles/cf-cli-resource/Dockerfile
- Update dockerfile for cf cli resource
Updating Dockerfile
=> update Dockerfile for cf cli resource

ci/container/pages/zap/vars.yml, ci/container/pipeline.yml
- add pages zap image
Adds another hardened image for CI use
=> add pages zap image

container/import-scan.sh
- Add missing trailing \
-
-
Add missing \
=> add missing \

container/pipeline-pages.yml
- Fixes a copy paste error for on_failure and on_success
Fixing a copy paste error
=> update on_failure and on_success

ci/container/internal/concourse-http-jq-resource/vars.yml, ci/container/pipeline.yml
- Adding a new image as part of https://github.com/cloud-gov/private/issues/1438
- Needed to harden the Dockerfile and likely will need to modify the `check` file so pulling this in now.
-
None
=> Adding concourse-http-jq-resource

ci/container/internal/base_vars.yml, ci/container/internal/bosh-deployment-resource/vars.yml, ci/container/internal/cf-resource/vars.yml, ci/container/internal/concourse-http-jq-resource/vars.yml, ci/container/internal/cron-resource/vars.yml, ci/container/internal/csb/vars.yml, ci/container/internal/external-domain-broker-migrator-testing/vars.yml, ci/container/internal/external-domain-broker-testing/vars.yml, ci/container/internal/general-task/vars.yml, ci/container/internal/github-pr-resource/vars.yml, ci/container/internal/github-release-resource/vars.yml, ci/container/internal/legacy-domain-certificate-renewer-testing/vars.yml, ci/container/internal/oci-build-task/vars.yml, ci/container/internal/playwright-python/vars.yml, ci/container/internal/pulledpork/vars.yml, ci/container/internal/s3-resource/vars.yml, ci/container/internal/s3-simple-resource/vars.yml, ci/container/internal/slack-notification-resource/vars.yml, ci/container/internal/ubuntu-hardened/vars.yml, ci/container/pipeline.yml
- Second pass at https://github.com/cloud-gov/common-pipelines/pull/132, but with one critical fix: The order of `var_files` is reversed. See https://github.com/concourse/concourse/issues/5455
None.
=> Attempt 2: Simplify container pipeline creation with base vars file

container/pipeline-internal.yml
=> Try inlining task config instead of using file

container/pipeline-internal.yml
=> Add missing task config field

container/clamav-scan.sh, container/clamav-scan.yml, container/pipeline-external.yml, container/pipeline-internal.yml, container/pipeline-pages.yml
- Adds a script to run clamav scans whenever an image is built
Needed to run a clamav scan on each image. Later we will add gating on pass/fail of the scan
=> run clamav scan on images

container/clamav-scan.sh, container/clamav-scan.yml, container/pipeline-internal.yml, container/pipeline-pages.yml
- Adds clamav scan to other jobs in the pipeline
- Ensures script runs as root user
Making sure the scan runs in the right pipeline jobs
=> Update clamav scan

container/pipeline-external.yml, container/pipeline-internal.yml, container/pipeline-pages.yml
- Cleaning up the container pipelines by removing unneeded gets, making sure that tasks that can run in parallel do, and removing unneeded on_success steps
Small changes to make the pipelines cleaner and perform better. Will also make it easier to add failure conditions on individual tasks.
=> clean up tasks and improve pipelines

ci/container/internal/cg-csb/vars.yml
- I started using brokerpak-topic for something unrelated.
None.
=> Switch topic branch for SES brokerpak work

ci/container/external/bosh-io-stemcell-resource/vars.yml, container/dockerfiles/bosh-io-release-resource/Dockerfile
- Adding un-saved references to local container from last PR
- Correcting filename and removing all code for cleanup
Running latest code reduces risks
=> fixing missing variables

container/clamav-scan.sh
- Installs clamav-daemon so that config files are created properly
- Excludes /sys directory from scan since it causes failures and shouldn't need to be scanned anyways
Updating clamav scan so that it no longer has warnings or errors
=> install clamav-daemon for config files and exclude directory from scan

ci/container/internal/hardened-stack/vars.yml
- Corrects the current version of cflinuxfs4
None
=> Correct version of cflinuxfs4

ci/container/internal/ubuntu-hardened-stig/vars.yml, ci/container/pipeline.yml
- This will create a pipeline for our new ubuntu-hardened-stig image
- It will use the disa-stig branch of the ubuntu-hardened repo
- It will use the tailor-stig.xml file for the audit task
Creating a separate stig image for proper testing
=> create pipeline for the new ubuntu-hardened-stig image

ci/container/internal/paketo-jammy-full-hardened-candidate/vars.yml, ci/container/pipeline.yml
- Adds a pipeline to harden the Paketo Jammy Full stack
None
=> add hardened paketo stack

ci/container/internal/paketo-jammy-full-hardened-candidate/vars.yml
- drops the version from the base image in hopes this see all versions
None
=> drop base version

ci/container/internal/zap-runner/pipeline-internal.yml, ci/container/internal/zap-runner/vars.yml
- Updated repo to zap-runner for zap scans 
-
-
Adding zap scanner
=> add zap-runner

ci/container/internal/clamav-rest-candidate/vars.yml
- Switches to use the main branch. 
None. All tested on the develop branch
=> use main branch

ci/container/internal/paketo-jammy-full-hardened-candidate/vars.yml
- Use ssh git url (private repo)
none
=> private repo
