- README.md
- container/README.md
- container/oci-build.yml
- container/pipeline.yml
- container/vars.yml
Retrying this PR since I messed up the last one with a bad force push. (Thank goodness for the reflog.)
- Support building images using a new `container` common pipeline.
- Related to https://github.com/cloud-gov/product/issues/2567. 
Uses same 3rd party containers as other steps. To be addressed later in the epic.
> Build OCI images with common pipeline

- container/oci-build.yml
- container/parse_cis_audit_html.py
- container/pipeline.yml
- container/usg-audit.sh
- container/usg-audit.yml
- Run `usg audit` on the image output from the `oci-build` step.
- Largely ported from https://github.com/cloud-gov/container-scanning/blob/main/ci/audit-ecr-container.yml and related files
None.
> Port container auditing script from container-scanning

- container/grype.yaml
- container/oci-build.yml
- container/pipeline.yml
- container/scan-image.sh
- container/scan-image.yml
- Ports image scanning work from container-scanning repository largely as-is with minimal changes to work in common-pipelines model
- Enable OCI build cache to speed image builds
- Make source repository updates a trigger so pipelines are updated with new vars
CVE output is sensitive but is only output to Concourse …
> Scan image for CVEs with Grype

- container/pipeline.yml
- Replicate the build, audit, scan steps from main pipeline
- Push failure notifications to Slack instead of the pull request
Relates to https://github.com/cloud-gov/product/issues/2567. 
No new considerations.
> Build commits to main branch

- container/cve-check.sh
- container/cve-check.yml
- container/grype.yaml
- container/pipeline.yml
- See title.
- Ported from container-scanning.
- Related to https://github.com/cloud-gov/product/issues/2567.
None. CVE information is printed to logs in Concourse online, which is only accessible to platform operators.
> Filter CVE scan results on PR and merge to main

- container/example/pipeline.yml
- container/pipeline.yml
- Changes the example path for the vars file to match up with what is commonly used in our pipelines
None, just updating an example file
> Change example path to one that is most commonly used

- container/usg-audit.sh
- See title
None, just a change to reduce logging output.
> Make audit step output more readable by making apt operations quieter

- README.md
- container/README.md
- container/pipeline.yml
- Push images to ECR on merge to main when audit and scan are successful
- Tag images with git short hash (e.g. 282e38a)
- Tested successfully with `use-common-pipelines` repository in Concourse.
- Resolves https://github.com/cloud-gov/product/issues/2567
Pushing images to our private registry is in line with the …
> Push on merge

- container/pipeline.yml
- Update audit task to run as privileged user to fix some cis failures
Running as privileged user allows cis audit to run commands it cannot run under a namespaced user
> Run audit as privileged user

- container/pipeline-external-repository.yml
- container/pipeline.yml
- See title
None, refactor only.
> Parallelize all 'get' steps

- README.md
- container/tailor.xml
- container/usg-audit.sh
- Adds tailoring file to customize CIS Audit
- Updates usg audit command to use tailoring file
The tailoring file is a list of rules generated by the usg command that anyone can get if they make a ubuntu pro account. The only reason why we change a rule from true to false is if it is something that doesn't apply to …
> Add tailoring

- container/pipeline-external-repository.yml
- container/pipeline.yml
- Adds a continuous scan that runs once daily
- Posts notification to slack on success and fail so we can track for auditing purposes (keep record in slack in case pipeline gets deleted)
This continuous scan meets our requirements of scanning our containers at least once every 30 days
> Add continuous scanning

- container/oci-build.yml
- This adds the `ARG DEBIAN_FRONTEND=noninteractive` line to any dockerfile, allowing the build to continue rather than waiting for user input
Setting 'DEBIAN_FRONTEND' as an ARG in each dockerfile is better than setting it as an ENV in our base image, as the ARG only applies to the build, and won't cause any …
> Adds ARG line to dockerfile after base image has been called

- container/grype.yaml
- Updates the grype ignore list with the CVE for the JWT package that is a false positive. It is alerting on version number, but Ubuntu uses a different version number for their patch.
This CVE is already patched on our system, so listing it here should cause no issues.
> Update grype ignore list

- container/dockerfiles/git-resource/Dockerfile
- container/oci-build.yml
- This creates a common directory for any Dockerfiles we need to modify for external concourse resources
- This also changes the oci-build script back to just running build, as we don't need the extra scripts around it using the Dockerfile method
None, this just adds an easier method for hardening external …
> Add dockerfiles

- container/oci-build.yml
- See title
None, just adds common-pipelines as input to the oci-build task so the Dockerfile can be found
> add common-pipelines as input

- container/cve-check.yml
- container/pipeline-external-repository.yml
- container/pipeline.yml
- container/scan-image.yml
- Using `image` when calling the scan task interferes with the image output by the oci-build, so this goes back to specifying the image in the task files themselves
None, just fixes a pipeline issue
> Switch back to specifying image in task file

- container/dockerfiles/github-pr-resource/Dockerfile
- Adds dockerfile with modifications so that we can harden the external github-pr-resource
Adding another resource to harden and scan
> Add dockerfile for github-pr-resource

- container/dockerfiles/semver-resource/Dockerfile
- Created the semver-resource dockerfile.
-
-
This allows us to use a hardened `semver-resource`
> Created the semver-resource dockerfile.

- container/dockerfiles/github-pr-resource/Dockerfile
- Updates dockerfile to install git-crypt using apt rather than the repo install script
None, this just fixes an issue with building the image
> Install git-crypt from package manager

- container/README.md
- container/examples/cloud-gov-repo/ci/vars.yml
- container/examples/external-repo/ci/vars.yml
- container/oci-build.yml
- container/pipeline-external-repository.yml
- container/pipeline.yml
- Updates common-pipelines resource to only update when there is a change to the container directory, and to ignore any changes to the dockerfile directory
- Adds a docker-file resource that pipelines can use to trigger on a Dockerfile change
- Parameterize common-pipelines trigger value so that we can set on each pipeline whether we want it to trigger on updates. This should allow us to keep pipelines from triggering once for common-pipeline changes, and then again when the ubuntu-hardened image is created.
- Updates README
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. …
> Streamline pipelines

- container/dockerfiles/email-resource/Dockerfile
- After further research into the code this cert doesn't appear to be used
Removing certificate line as it doesn't appear to be necessary
> remove unneeded certificate line

- container/pipeline.yml
- Updates pull-request resource type to use our hardened github-pr-resource
Updates another resource to use our hardened image
> Update pull-request resource type

- container/dockerfiles/cf-cli-resource/Dockerfile
- Sets up dockerfile for cf-cli-resource
Makes it so cf-cli-resource uses our hardened base image
> add dockerfile for cf-cli-resource

- README.md
- container/README.md
- Related to https://github.com/cloud-gov/product/issues/2535
- Add architecture diagram for container pipeline
- Move grype exceptions to container-specific README
None; documentation of public code
> Container docs: Add architecture diagram, move grype exceptions

- ci/container/pipeline.yml
- See title. Without this, updates to src can trigger a run of the internal and external jobs before the pipeline has re-set itself.
None.
> Trigger jobs only after set-self has run to ensure current src is used

- README.md
- Update the readme to reflect the current usage of the container pipeline. Future common pipelines will be used the same way.
None.
> Root README is out of date with current usage

- container/pipeline-external.yml
- container/pipeline-internal.yml
- Removes the software inventory task from the continuous scan so that job doesn't error out
None, just removing a task that causes an error
> remove software inventory task from continuous scan

- ci/container/pages/dind-v25/vars.yml
- ci/container/pages/node-v20/vars.yml
- ci/container/pipeline.yml
- container/README.md
- container/pipeline-pages.yml
- Creates a separate Pages container pipeline
- Deploys individual container pipelines to the Pages Concourse team
- Add a docker in docker image for Pages testing
- Add a node image
Adds a new Pages specific pipelines for container hardening and scanning.
> feat: Add pages pipeline for containers

- container/pipeline-external.yml
- container/pipeline-internal.yml
- Sends notification to cg-platform channel when image build fails
Sending the notification to this channel will increase the likelihood that we notice the issue and fix it
> change slack channel

- ci/container/pipeline.yml
- container/pipeline-pages.yml
- Adds a PR job to run the scan and audit tasks for the Pages image container pipeline template
- Adds Pages GPG signed keys to source code
- Adds Pages gpg key check for image source code
- Runs scan/audit on non-forked PRs to Pages images
> feat: Add job to run scans and audit to Pages containers

- ci/container/internal/cf-resource/vars.yml
- ci/container/pipeline.yml
- Moved cf-resource to internal
- Updated source to point to new cloud-gov location
-
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the output, which can prevent unintentional leaks of sensitive data.
This should improve security by moving cloud-gov to our internal fork using hardened pipelines and utilizing more of our internal checks in the process.
> moved cf-resource to internal and updated src-repo

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Updates failure notifications to send to a channel with more visibility
Failures will be sent to the correct channel so we have more visibility
> Update notification channel

- container/pipeline-external.yml
- container/pipeline-internal.yml
- [update internal pipelines to set PR status on success](https://github.com/cloud-gov/common-pipelines/commit/5896aae46ff7a2b425091385621cb3278c85318c). Without this, PR status checks are never marked as complete
- [update notification channels to not be hardcoded](https://github.com/cloud-gov/common-pipelines/commit/3bea05ba56aecf8ce2c1082b09c28099124532f4)
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can …
> Update pipeline templates

- ci/container/external/cloud-service-broker/vars.yml
- ci/container/pipeline.yml
- container/dockerfiles/cloud-service-broker/Dockerfile
- Build a hardened image for the cloud service broker so we can experiment with it and eventually use it in our environment.
- Related to https://github.com/cloud-gov/product/issues/2943
Uses our existing process for building a new external project using an internally maintained docker image.
> Build hardened docker image for cloud-service-broker

- container/dockerfiles/cloud-service-broker/Dockerfile
- No other images have WORKDIR set, and Concourse is unable to find inputs for this pipeline only. I suspect WORKDIR is (incorrectly) being used instead of the typical Concourse temp directory.
None
> Try fixing build by removing workdir

- ci/container/external/cloud-service-broker/vars.yml
- container/dockerfiles/cloud-service-broker/Dockerfile
- base_image arg must be at the top of the Dockerfile. Not sure why.
- DOCKERFILE param is required. Without it, oci-build uses the Dockerfile in the src repo.
- Add the rest of the Dockerfile back now that I've tested it
None
> Fix docker build and usg audit

- container/dockerfiles/cloud-service-broker/Dockerfile
...since our RDS instance are in GovCloud.
Cert bundle is sourced from an Amazon-owned domain and referenced from their documentation.
> Replace commercial CA cert with GovCloud cert bundle

- container/dockerfiles/cloud-service-broker/Dockerfile
- See title.
- Related to https://github.com/cloud-gov/product/issues/2943
None.
> Set correct extension so certs are detected by update-ca-certificates

- container/import-scan.sh
- container/import-scan.yml
- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Adds script to import grype scan into defect dojo
Importing CVE scans of container images
> Add script to import scan to defect dojo

- ci/container/pages/playwright-v1/vars.yml
- use node as base for playwright image
uses another hardened image as the base
> use node as base for playwright image

- ci/container/internal/playwright-python/vars.yml
- add internal pipeline configuration for playwright-python image: https://github.com/cloud-gov/playwright-python
This configuration will create the pipeline to generate a hardened image for running Playwright Python in CI
> add internal pipeline configuration for playwright-python image

- ci/container/pipeline.yml
- see title
The playwright-python pipeline will created a hardened image that can be used in CI for running Python Playwright tests
> add variable to ensure that playwright-python pipeline is created

- ci/container/internal/csb/vars.yml
- Related to https://github.com/cloud-gov/product/issues/2943
None.
> Set BUILD_ENV arg so ZScaler certs are not copied to image

- ci/container/internal/oci-build-task/vars.yml
- ci/container/pipeline.yml
- Add oci-build-task to our internal pipelines
Adds pipeline to harden another image
> adds oci-build-task

- ci/container/external/cf-cli-resource/vars.yml
- ci/container/external/cloud-service-broker/vars.yml
- ci/container/external/email-resource/vars.yml
- ci/container/external/git-resource/vars.yml
- ci/container/external/registry-image-resource/vars.yml
- ci/container/external/semver-resource/vars.yml
- ci/container/external/time-resource/vars.yml
- container/pipeline-external.yml
- I'd like to be able to build cloud service broker images on each tag instead of each commit, since commits to the main branch can break the build. To support this, I've factored out the `src` repo configuration to the vars files, which allows setting either a branch to watch for every commit, or a tag regex pattern to match against.
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional …
> Support building images on tag instead of commit in source repository

- ci/container/internal/bosh-deployment-resource/vars.yml
- ci/container/pipeline.yml
- Adds bosh-deployment-resource to the container hardening and scanning pipeline
Adds another image for container hardening and scanning
> adding bosh-deployment-resource

- ci/container/internal/github-release-resource/vars.yml
- ci/container/pipeline.yml
- Adds github-release-resource to scanning and hardening pipeline
Setting up another image for hardening
> add github-release-resource

- ci/container/external/cf-cli-resource/vars.yml
- ci/container/external/cloud-service-broker/vars.yml
- ci/container/external/email-resource/vars.yml
- ci/container/external/git-resource/vars.yml
- ci/container/external/registry-image-resource/vars.yml
- ci/container/external/semver-resource/vars.yml
- ci/container/external/time-resource/vars.yml
- git-resource needs uri, not url, to properly grab resources
-
-
Update external pipelines so that getting the src no longer fails
> url should be uri

- ci/container/external/bosh-io-release-resource/vars.yml
- ci/container/pipeline.yml
- Adds pipeline to harden bosh-io-release-resource
Adds pipeline to harden another image
> Add bosh io resource

- ci/container/internal/pulledpork/vars.yml
- ci/container/pipeline.yml
- Adds pipeline to harden pulledpork image
Adding pipeline to harden image
> add pipeline for pulledpork image

- container/import-scan.sh
- Include date to have easier organization of grype findings in defectdojo
Adding date to improve organization of findings
> update scan import to include date

- container/import-scan.sh
- Remove extra quote
Removes an extra quote
> remove extra quote

- container/scan-image.sh
- Use only-fixed flag
Adds flag to show only vulns with fixes available
> add only-fixed flag

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
Also format pipelines with prettierd. 
The formatting has obfuscated the change; it adds the following to each `put: image` step:
```
get_params:
skip_download: true
```
None
> Make pipeline run faster by skipping unnecessary image download

- container/import-scan.sh
- This setting is needed to close old findings that were seen in old scans but are no longer found in new scans
Fixing scan import to close old findings
> update import scan to close old findings across product

- container/import-scan.sh
- Add the close_old_findings option because the default is different between the reimport and import api calls
Setting needed to close old findings
> set close_old_findings option for import

- ci/container/pages/dind/vars.yml
- ci/container/pipeline.yml
- Bump versions associated with the docker in docker image
Updates to the latest version of Docker Engine
> chore: bump dind major version

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Remove iaas tag as it is no longer needed
Removing the iaas tag after updating concourse permissions
> remove iaas tag

- container/dockerfiles/cf-cli-resource/Dockerfile
- Patch the CF CLI v7 version which uses `golang.org/x/net v0.28.0`, the older version 0.22.0 is being flagged by DD
-
-
Moves to a more recent version of the CF CLI to be used in the concourse containers
> Patch CF CLI to newest, 7.7.12

- container/dockerfiles/cf-cli-resource/Dockerfile
- Patch the CF CLI v8 version which uses `golang.org/x/net v0.28.0`, the older version 0.22.0 is being flagged by DD
- The original DD scan only noted the v7 file location.  Had to patch and rerun to find the second location, hence this PR
-
Moves to a more recent version of the CF CLI to be used in the concourse …
> Patch CF CLI to newest for v8, 8.8.0

- container/oci-build.yml
- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Updates remaining resource to use hardened images
Use hardened images
> use hardened images

- ci/container/internal/external-domain-broker-testing/vars.yml
- ci/container/internal/external-domain-broker/vars.yml
- ci/container/pipeline.yml
- Adds a pipeline to harden the image used in the external-domain-broker repo
Hardening another image
> Add external domain broker

- container/usg-audit.sh
- container/usg-audit.yml
- Set the script to run as root in case there's an image that starts up as another user
- Use `python3 -m pip` so that bs4 is installed properly for use by the script
Fixing the audit script to work for all images, regardless of user
> Fix audit image script

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Removes the fire_immediately param from the `monthly` resource so that it doesn't fire every time we update the pipeline
- We only want the job to run once a month
Updating `monthly` resource
> removes the fire_immediately param

- container/dockerfiles/cloud-service-broker/Dockerfile
- Upstream can change their required Go version in go.mod, breaking our build unless we always use the latest version.
None.
> Always use latest golang 1.x image to build cloud-service-broker

- ci/container/internal/external-domain-broker-migrator-testing/vars.yml
- ci/container/pipeline.yml
- Adds pipeline for the external-domain-broker-migrator-testing image
Adding another hardened image
> adding pipeline for external-domain-broker-migrator-testing image

- ci/container/internal/legacy-domain-certificate-renewer-testing/vars.yml
- ci/container/pipeline.yml
- Sets up pipeline to harden the legacy-domain-certificate-renewer-testing image
Setting up another hardened image pipeline
> adding pipeline for legacy-domain-certificate-renewer-testing image

- ci/container/internal/base_vars.yml
- ci/container/internal/bosh-deployment-resource/vars.yml
- ci/container/internal/cf-resource/vars.yml
- ci/container/internal/concourse-http-jq-resource/vars.yml
- ci/container/internal/cron-resource/vars.yml
- ci/container/internal/csb/vars.yml
- ci/container/internal/external-domain-broker-migrator-testing/vars.yml
- ci/container/internal/external-domain-broker-testing/vars.yml
- ci/container/internal/general-task/vars.yml
- ci/container/internal/github-pr-resource/vars.yml
- ci/container/internal/github-release-resource/vars.yml
- ci/container/internal/legacy-domain-certificate-renewer-testing/vars.yml
- ci/container/internal/oci-build-task/vars.yml
- ci/container/internal/playwright-python/vars.yml
- ci/container/internal/pulledpork/vars.yml
- ci/container/internal/s3-resource/vars.yml
- ci/container/internal/s3-simple-resource/vars.yml
- ci/container/internal/slack-notification-resource/vars.yml
- ci/container/internal/ubuntu-hardened/vars.yml
- ci/container/pipeline.yml
- 6 of the 8 required variables for pipelines almost always have the same values. This PR extracts them out to a vars file that gets referenced before the pipeline-specific one. Values in the pipeline-specific file override those in the base file.
- Start with internal pipelines only; I'll do external in a follow-up PR
- See https://concourse-ci.org/set-pipeline-step.html#set-pipeline-step
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be …
> Make configuring pipelines simpler by factoring out common vars

- ci/container/external/base_vars.yml
- ci/container/external/bosh-io-release-resource/vars.yml
- ci/container/external/bosh-io-stemcell-resource/vars.yml
- ci/container/external/cf-cli-resource/vars.yml
- ci/container/external/cloud-service-broker/vars.yml
- ci/container/external/email-resource/vars.yml
- ci/container/external/git-resource/vars.yml
- ci/container/external/openresty/vars.yml
- ci/container/external/pool-resource/vars.yml
- ci/container/external/registry-image-resource/vars.yml
- ci/container/external/semver-resource/vars.yml
- ci/container/external/time-resource/vars.yml
- ci/container/pipeline.yml
- This is the same change as https://github.com/cloud-gov/common-pipelines/pull/134, but for the external pipelines. One more to follow for Pages.
None.
> Extract default variables to separate file in external pipelines

- ci/container/external/registry-image-resource/vars.yml
Rolling back for pages deploy issue: https://ci.fr.cloud.gov/teams/pages/pipelines/cf-build-tasks/jobs/deploy/builds/58?vars.deploy-env=%22dev%22
Rolling back until the issue can be worked out.
> rollback for pages deployment issue

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Add `serial_groups` to jobs so that they do not run in parallel, which should help reduce load on concourse
Reducing load on concourse
> Serialize jobs

- ci/container/internal/base_vars.yml
- container/pipeline-internal.yml
- container/static-analysis.yml
- Authors of Docker images may want to run static analysis tools as part of their PR workflow to ensure quality. This change allows them to configure a command and arguments that can run a static analyzer. 
- Authors can include a script in their repo and run that script, or directly invoke any command available in the `general-task` image. 
- The design could change in the future. For instance, if many images with a given language all configure the same static analyzer, we could instead provide a `static-analysis-language` var, and maintain a script relevant to the language that gets invoked behind the scenes. 
- We could also add more steps like this in the future: For example, `run-tests` step. 
- Related to https://github.com/cloud-gov/product/issues/3112
- For any logging statements, …
> Add optional static analysis step to PR job

- container/pipeline-internal.yml
- I forgot it's 'container' singular, not 'containers' plural.
None.
> Fix misspelling in static-analysis step field

- ci/container/internal/base_vars.yml
- container/pipeline-internal.yml
- container/static-analysis.yml
The current method results in an error:
failed to create task config from bytes common-pipelines/container/static-analysis.yml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field TaskRunConfig.run.args of type []string
The string in question must be ((args)) inside the task file, but I can verify in the pipeline itself that ((static-analysis-args)) is a []string, so I'm not sure why the slice aspect is getting lost. This attempt may not work, but the nature of our Concourse setup makes it difficult to test by any other method.
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements …
> Attempt to fix variable type mismatch by inlining references to vars

- ci/container/internal/csb/vars.yml
- See title. Right now I think a trivy finding will cause the task step to fail, which is desirable. Since this is just a PR, the results don't go anywhere (e.g. Defect Dojo). If we run it on the `main` in the future, they could be uploaded.
- Related to https://github.com/cloud-gov/product/issues/3112
None.
> Use trivy to scan the CSB brokerpaks for configuration issues

- ci/container/internal/csb/vars.yml
- Per the comment, we get rate limited trying to pull this image from GHCR. Since it's not being run as a container, I don't think it needs to be hardened, but if we want to use Trivy that way, we should probably mirror it to ECR anyway. Regardless, the checks database is already included, so skip the download for now.
- The better solution is to follow [Trivy's instructions](https://aquasecurity.github.io/trivy/v0.56/docs/advanced/air-gap/) for mirroring the images to our own container registry. I will make a follow-up ticket for this, but I want to get it working as a baseline first.
- Are log statements using a logging library with a logging level set? Setting a logging level means that log …
> Skip downloading Trivy check database, with explanation

- ci/container/internal/csb/vars.yml
- For reasons I couldn't diagnose, the trivy command failed with the previous args because it could not walk the file system. I tested this version of the command by overwriting the pipeline in Concourse and it works. 
- Related to https://github.com/cloud-gov/product/issues/3112
None.
> Fix step failing to stat directory

- ci/container/internal/base_vars.yml
- ci/container/internal/csb/vars.yml
- container/pipeline-internal.yml
- Today, I build topic branches by manually setting the pipeline, but it gets overwritten periodically. This allows switching the branch more permanently.
Nothing new. Developers can already change this manually from the CLI.
> Make src branch configurable so images can be built from a topic branch

- ci/container/internal/base_vars.yml
- ci/container/internal/csb-docproxy/vars.yml
- ci/container/pipeline.yml
- container/oci-build.yml
- container/pipeline-internal.yml
- This change adds a new feature to the OCI build step for the internal pipeline: The ability to specify a builder image. Many docker images are built using multi-stage builds: First, a more fully-featured builder image is used to build an application; next, the build artifacts are copied to a smaller final base image. 
- The motivating use case is building a Go application related to the Cloud Service Broker. A builder step with the Go toolchain builds the application, and a final step copies the binary to our standard base image. 
- Further motivation for the builder image here: https://github.com/cloud-gov/product/issues/3216#issuecomment-2536272676
- Related to https://github.com/cloud-gov/product/issues/3216
- For any logging statements, is there any chance that they could be logging …
> Build csb-docproxy image with new builder image feature

- container/pipeline-internal.yml
- Fix to previous PR, which was missing get steps.
See previous PR.
> Add missing get steps for builder image

- ci/container/internal/base_vars.yml
- ci/container/internal/csb-docproxy/vars.yml
- container/oci-build.yml
- container/pipeline-internal.yml
- The change in https://github.com/cloud-gov/common-pipelines/pull/151 broke external pipelines due to missing input.
- The csb-dockerproxy was also broken due to the Dockerfile being located in a subfolder.
- This change also reduces rebuilds of images. 
None.
> Fix build errors related to builder image

- ci/container/internal/csb-docproxy/vars.yml
- ...Not in common-dockerfiles, which is the consumer of this param.
None.
> Drop redundant dockerfile path param, since dockerfile is in src

- ci/container/internal/csb-docproxy/vars.yml
- Without this, the oci build step tries copying files from the repo root instead of the `docproxy/` directory.
None.
> Use CONTEXT instead of DOCKERFILE to build from correct working dir

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Removing the `get: general-task` steps from the pipelines as it is not necessary to get the general-task resource for the subsequent tasks
- Removing the `general-task` resource since we will no longer have any get steps that require it
Removing unneeded code to improve performance
> remove get of the general-task resource

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Adds a job to scan the source code (for vulnerabilities, misconfigurations, and secrets) that will be used to build the container image before running any other job
Improving security by scanning the code we pull in
> Add code scanning

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
The previous behavior skips downloading the image after uploading it to ECR, but still takes some time - up to 25 seconds, based on a quick review of one pipeline - to execute the noop get. This change entirely removes the get, which is not necessary since the image is not used after the put step.
None.
> Cut a few seconds from pipeline by entirely skipping image get after put

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- container/usg-audit.sh
- container/usg-audit.yml
- Adds a task to upload the usg audit files to S3 whenever an image is built
This helps to meet compliance requirements about storing benchmark scan results
> Export usg audit results

- container/dockerfiles/cf-cli-resource/Dockerfile
- Updates cf cli v7 and v8 for the cf-cli-resource
Updating cf cli versions for the cf-cli-resource image
> updating cf cli versions

- ci/container/external/bosh-io-release-resource/vars.yml
- container/dockerfiles/bosh-io-release-resource/dockerfile
- Move to use local/in-repo dockerfile for bosh-io-resource
- Pulling latest binary from GH instead of 9 year old Docker image based on v1 schema
- I will also make a PR to upstream so if we want to revert back to upstream once PR merged we can
Running latest versions of code reduces risks
> Fix jq error in bosh-io-resource/move to local Dockerfile from upstream

- ci/container/external/bosh-io-release-resource/vars.yml
- ci/container/external/bosh-io-stemcell-resource/vars.yml
- Fixing the bosh-io-release resource and not stemcell
Running latest code reduces risks
> fixing the correct resource

- ci/container/external/registry-image-resource/vars.yml
- container/dockerfiles/registry-image-resource/Dockerfile
- Updates the registry-image-resource to use our own Dockerfile
Upstream Dockerfile is no longer compatible with our base hardened image
> update registry-image-resource to use our own Dockerfile

- ci/container/internal/hardened-stack/vars.yml
- ci/container/pipeline.yml
- Adds a hardened-stack internal pipeline based on the https://github.com/cloud-gov/ubuntu-hardened repo. 
- The base image is the cloudfoundry/cflinuxfs4 image. This is the current stack running in CloudFoundry. 
Centralizes security hardening in the https://github.com/cloud-gov/ubuntu-hardened.
> Adds a hardened-stack internal pipelines

- ci/container/external/base_vars.yml
- ci/container/internal/base_vars.yml
- ci/container/pages/base_vars.yml
- container/parse_usg_audit_html.py
- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- container/tailor-stig.xml
- container/usg-audit.sh
- This makes our audit script more dynamic by being able to specify what tailoring file we want to use with a variable
- This also adds a new tailoring file based off of disa-stig requirements
- Updates/removes any references to CIS to make this more generic
Making our audit script work with disa-stigs
> make audit script more dynamic

- ci/container/external/pool-resource/vars.yml
- ci/container/external/time-resource/vars.yml
- container/dockerfiles/pool-resource/Dockerfile
- container/dockerfiles/time-resource/Dockerfile
- Update pool-resource and time-resource to use our own version of the Dockerfile since upstream switched to wolfi
Updating pipelines to use our own dockerfiles
> use our own dockerfiles for resources

- container/oci-build.yml
- Use build secrets rather than args for token
Build secrets are a more secure method than args
> use build secrets rather than build args for token

- ci/container/internal/playwright-python/vars.yml
- ci/container/pages/base_vars.yml
- ci/container/pages/dind/vars.yml
- ci/container/pages/nginx-v1/vars.yml
- ci/container/pages/node-v20/vars.yml
- ci/container/pages/postgres-v15/vars.yml
- ci/container/pages/python-v3.11/vars.yml
- ci/container/pages/redis-v7.2/vars.yml
- ci/container/pages/zap/vars.yml
- container/pipeline-pages.yml
- Removes the dockerfile trigger for playwright-python since it is not needed
- Sets the dockerfile trigger to false in the pages base_vars.yml file since we also do not need this trigger for pages pipelines. The dockerfile trigger is only necessary if we have set up our own dockerfile for a repo in common-pipelines
- Adds a src-path check for the pages repo, so it only triggers when the src for the relevant pages image is updated
- These changes should help with the issue of disappearing resources
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging …
> remove dockerfile triggers

- container/pipeline-internal.yml
- Adds input mapping so oci-build-task in the stig test job doesn't break
None, fixing broken task
> add input mapping

- ci/container/internal/clamav-rest/vars.yml
- Sets the build args file path relative to the concourse build, not the oci build context. 
None
> context  doesn't apply to build args file path

- ci/container/internal/clamav-rest/vars.yml
- Stig tailoring file for usg audits. We are using the stig base image. 
Tailoring file needs to match the image.
> use the stig tailoring file as the main job uses the stig image

- ci/container/external/semver-resource/vars.yml
- container/dockerfiles/semver-resource/Dockerfile
- This switches the semver github resource to the official concourse resource
- This also updates official the Dockerfile to incorporate the changes from the official concourse resource while still using our base ubuntu image
- This shouldn't affect any current pipelines, as only a couple of them reference the resource, but they don't actually get used
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent …
> update semver resource

- ci/container/external/base_vars.yml
- ci/container/internal/base_vars.yml
- ci/container/internal/cf-resource/vars.yml
- ci/container/pages/base_vars.yml
- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Adds a task for running image build tests to all pipelines that by default only runs an echo command
- Sets this task only in the stig testing job for now
- Sets up a test for the cf-resource
Setting up task to be able to run tests for all our container images
> adds build-test task

- container/pipeline-external.yml
- container/pipeline-internal.yml
- container/pipeline-pages.yml
- Remove serial_groups option from test-stig-build job so it doesn't keep our regular jobs from running
None, improves speed of moving updates to containers through the pipelines
> remove stig-build job from serial group

- ci/container/external/git-resource/vars.yml
- ci/container/external/pool-resource/vars.yml
- ci/container/external/time-resource/vars.yml
- ci/container/internal/github-release-resource/vars.yml
- sets up test jobs for those container images that already have testing we can use in our own pipelines
Adding testing to our container images
> Add tests for builds

- ci/container/external/bosh-io-release-resource/vars.yml
- ci/container/external/bosh-io-stemcell-resource/vars.yml
- ci/container/external/registry-image-resource/vars.yml
- ci/container/external/semver-resource/vars.yml
- ci/container/internal/bosh-deployment-resource/vars.yml
- ci/container/internal/s3-resource/vars.yml
- Enables tests in disa-test and PR pipeline jobs for the following pipelines:
- bosh-io-release-resource
- bosh-io-stemcell-resource
- registry-image-resource
- semver-resource
- bosh-deployment-resource
- s3-resource
Enabling tests for pipelines
> enables tests for more image builds

- ci/container/internal/concourse-http-jq-resource/vars.yml
- Update concourse-http-jq-resource to use stig base image
> switch to stig base image for concourse-http-jq-resource

- ci/container/internal/bosh-deployment-resource/vars.yml
- Use the base stig image for the bosh-deployment-resource
Switching over to base stig image
> switch to stig base image for bosh-deployment-resource

- ci/container/internal/external-domain-broker-migrator-testing/vars.yml
- Update to use stig base image for the external-domain-migrator-testing resource
Update to use stigs
> use stig base image for external-domain-migrator-testing

- ci/container/internal/general-task/vars.yml
- Update to use stig base image for general-task resource
Update to use stigs
> use stig base image for general-task

- ci/container/internal/github-release-resource/vars.yml
- Update to use stig base image for github-release-resource
Updating to use stig
> use stig base image for github-release-resource

- ci/container/internal/oci-build-task/vars.yml
- Update to use stig base image for oci-build-task
Updating to use stig
> use stig base image for oci-build-task

- ci/container/internal/opensearch-dashboards-testing/vars.yml
- Update to use stig base image for opensearch-dashboards-testing
Update to use stigs
> use stig base image for opensearch-dashboards-testing

- ci/container/internal/opensearch-testing/vars.yml
- Update to use stig base image for opensearch-testing
Update to use stigs
> use stig base image for opensearch-testing

- ci/container/internal/playwright-python/vars.yml
- Update to use stig base image for playwright-python
Updating to use stigs
> use stig base image for playwright-python

- ci/container/internal/s3-resource/vars.yml
- Update to use stig base image for s3-resource
Updating to use stigs
> use stig base image for s3-resource

- ci/container/external/bosh-io-release-resource/vars.yml
- Update to use stig base image for bosh-io-release-resource
> use stig base image for bosh-io-release-resource

- ci/container/external/cf-cli-resource/vars.yml
- Update to use stig base image for cf-cli-resource
> use stig for cf-cli-resource

- ci/container/external/cloud-service-broker/vars.yml
- Update to use stig base image for cloud-service-broker
> use stig base image for cloud-service-broker

- ci/container/pages/dind/vars.yml
- Updates to use stig base image for the pages dind image
> use stig base image for pages dind

- ci/container/pages/nginx-v1/vars.yml
- Updates to use stig base image for pages nginx-v1 image
> use stig base image for pages nginx-v1

- ci/container/pages/node-v20/vars.yml
- Updates to use stig base image for pages node-v20 image
> use stig base image for pages node-v20

- ci/container/pages/redis-v7.2/vars.yml
- Updates to use stig base image for pages redis-v7.2 image
> use stig base image for pages redis-v7.2

- ci/container/pages/zap/vars.yml
- Updates to use stig base image for pages zap image
> use stig base image for pages zap

- ci/container/external/git-resource/vars.yml
- Removes running the build test for the git-resource as the upstream where we pull these tests from also fails
Removing build tests that appear to have never worked even in upstream
> remove git tests

- ci/container/internal/concourse-http-jq-resource/vars.yml
- ci/container/pipeline.yml
- Removes `concourse-http-jq-resource` from common-pipelines repo, this resource is no longer needed.
- Part of https://github.com/cloud-gov/private/issues/2688
-
This reduces the amount of code and images which need to be maintained
> Remove concourse-http-jq-resource
